// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-H1XHKOjLHJkHK74cvukRW_DcX5bdsU',
    appId: '1:657342568810:web:59d5fdaa4446b90968ad13',
    messagingSenderId: '657342568810',
    projectId: 'zirtavat-7f30d',
    authDomain: 'zirtavat-7f30d.firebaseapp.com',
    storageBucket: 'zirtavat-7f30d.appspot.com',
    measurementId: 'G-L4159KFXZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0wbYsq7miPi9-a4-wda69B1NtHmIYyA',
    appId: '1:657342568810:android:cddf3d9b376584af68ad13',
    messagingSenderId: '657342568810',
    projectId: 'zirtavat-7f30d',
    storageBucket: 'zirtavat-7f30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAL3iYUodhzyRqpOeycmCdtB3DTAZ11zE',
    appId: '1:657342568810:ios:19d7767e311f18a068ad13',
    messagingSenderId: '657342568810',
    projectId: 'zirtavat-7f30d',
    storageBucket: 'zirtavat-7f30d.appspot.com',
    iosBundleId: 'com.example.zirtavat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAL3iYUodhzyRqpOeycmCdtB3DTAZ11zE',
    appId: '1:657342568810:ios:ebe6636d804d7a0268ad13',
    messagingSenderId: '657342568810',
    projectId: 'zirtavat-7f30d',
    storageBucket: 'zirtavat-7f30d.appspot.com',
    iosBundleId: 'com.example.zirtavat.RunnerTests',
  );
}
